name: ctrl_sim
channels:
  - defaults
  - pyg
dependencies:
  - python=3.10
  - pip
  - jupyterlab
  - pip:
    - hydra-core
    - hydra-submitit-launcher
    - ipdb
    - seaborn
    - imageio
    - moviepy
    - opencv-python
    - gym
    - wandb
    - setproctitle
    - tensorboardX
    - pytest
    - flake8
    - pydocstyle
    - pyvirtualdisplay
    - ray
    - dm-tree
    - tabulate
    - torch==2.2.0
    - h5py
    - matplotlib
    - scipy==1.12.0
    - numpy==1.23.0
    - torch-ema
    - pytorch-lightning
    - torch_geometric
    - einops