hidden_dim: 256 # try 32, 64, 256, 512
map_attr: 3
num_road_types: 8
no_actions: False
num_heads: 8
num_reward_components: 3
dim_feedforward: 1024
dropout: 0.1
state_dim: 12
use_map: True
goal_dropout: 0.1
max_pool_map: True
supervise_moving: True
predict_rtg: True
attend_own_return_action: False
trajeglish: False
il: False
ctg_plus_plus: False
decision_transformer: False
